# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: yourrepo
  tag: versiontag
  pullPolicy: Always
