# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
backend:
  name: keepsafe-cloud-backend
  replicaCount: 1
  image:
    repository: clementgohlke/keepsafe-backend
    tag: 1
    pullPolicy: Always
  containerPort: 8080
  externalPort: 8080
frontend:
  name: keepsafe-cloud-frontend
  replicaCount: 1
  image:
    repository: clementgohlke/keepsafe-frontend
    tag: 1
    pullPolicy: Always
  containerPort: 80
<<<<<<< HEAD
  externalPort: 80
=======
>>>>>>> 3f19b4d43507790618f759bedca8d435326501be
