name: Release
on:
  push:
    branches:
      - main
      - master
      - frontend-v1
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test
      - run: docker build . -t "my-first-container:v0.0.1" 
      - run: docker tag my-first-container:v0.0.1 clementgohlke/exellys-case:${{github.run_attempt}}
      - run: docker login -u clementgohlke -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker push clementgohlke/exellys-case:${{github.run_attempt}}
  build-frontend:
    name: buildFrontEnd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: docker build . -t "clementgohlke/keepsafe-cloud-case:${{github.run_attempt}}" 
      - run: docker login -u clementgohlke -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker push clementgohlke/keepsafe-cloud-case:${{github.run_attempt}}