name: Release
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - id: install npm
        run: npm install
      - id: run unit tests
        run: npm test
      - id: build docker image
        run: docker build . -t "my-first-container:v0.0.1" 
      - id: tag docker image
        run: docker tag my-first-container:v0.0.1 clementgohlke/exellys-case:v1.0.0 # ${{github.event.head_commit.message}}
      - id: push image to dockerhub 
        run: docker push clementgohlke/exellys-case:v1.0.0 #${{github.event.head_commit.message}}