name: Release
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test
      - run: docker build . -t "my-first-container:v0.0.1" 
      - run: docker tag my-first-container:v0.0.1 clementgohlke/exellys-case:${{github.run_attempt}}
      - run: docker login -u clementgohlke -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker push clementgohlke/exellys-case:${{github.run_attempt}}